---
AWSTemplateFormatVersion: "2010-09-09"
Description: "Template for secure S3 bucket provisioning"

Parameters:
  BucketName:
    Type: String
    Description: "Bucket name must be globally unique"

  LoggingBucket:
    Type: String
    Description: "Destination bucket for logging"

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

      VersioningConfiguration:
        Status: Enabled

      Tags:
        - Key: "Env"
          Value: "Lab"

      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: "AES256"

      LoggingConfiguration:
        DestinationBucketName: !Ref LoggingBucket
        LogFilePrefix: "S3-logs"

  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 's3:*'
            Effect: Deny
            Resource: !Join
              - ''
              - - 'arn:aws:s3:::'
                - !Ref S3Bucket
                - /*
            Principal: '*'

Outputs:
  BucketName:
    Description: "S3 Bucket Name"
    Value: !Ref S3Bucket

  BucketArn:
    Description: "S3 Bucket Arn"
    Value: !GetAtt S3Bucket.Arn
